version: "2.4"
services:

  filebrowser:
    container_name: filebrowser
    restart: unless-stopped
    volumes:
      - ./:/srv
      - ./apps/filebrowser/:/database/
    ports:
      - '4746:80'
    image: filebrowser/filebrowser


  music-server:
    image: sentriz/gonic:latest
    container_name: music-svr
    restart: unless-stopped
    ports:
      - 4747:80
    volumes:
      - ./music/:/music:ro
      - ./apps/gonic/db:/data
      - ./apps/gonic/playlists:/playlists

  music-client:
    image: tamland/airsonic-refix:latest
    container_name: music-clt
    restart: unless-stopped
    ports:
      - 4748:80

  it-tools:
    container_name: it-tools
    image: 'corentinth/it-tools:latest'
    ports:
        - '4750:80'
    restart: unless-stopped
