services:

  reverse-proxy:
    image: caddy
    container_name: reverse-proxy
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./apps/caddy/caddyfile:/etc/caddy/Caddyfile
      - ./apps/caddy/data:/data
      - ./apps/caddy/config:/config
      - ./apps/lovergne.dev:/srv/lovergne.dev
    restart: unless-stopped

  filebrowser:
    container_name: filebrowser
    restart: unless-stopped
    volumes:
      - ./:/srv
      - ./apps/filebrowser/:/database/
    image: filebrowser/filebrowser

  music-server:
    image: sentriz/gonic:latest
    container_name: music-server
    volumes:
      - ./music/:/music:ro
      - ./apps/gonic/db:/data
      - ./apps/gonic/playlists:/playlists
    restart: unless-stopped

  music-client:
    image: tamland/airsonic-refix:latest
    container_name: music-client
    restart: unless-stopped

  feeds:
    container_name: feeds
    image: glanceapp/glance
    volumes: # Do not mount the entir app folder. It override the binary. 
      - ./apps/glance/config.yml:/app/glance.yml
      - ./apps/glance/assets:/app/assets
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped

  dev-tools:
    container_name: dev-tools
    image: 'corentinth/it-tools:latest'
    restart: unless-stopped
