services:

  filebrowser:
    container_name: filebrowser
    restart: unless-stopped
    volumes:
      - ./:/srv
      - ./apps/filebrowser/:/database/
    ports:
      - '5000:80'
    image: filebrowser/filebrowser

  music-server:
    image: sentriz/gonic:latest
    container_name: music-svr
    restart: unless-stopped
    ports:
      - 5001:80
    volumes:
      - ./music/:/music:ro
      - ./apps/gonic/db:/data
      - ./apps/gonic/playlists:/playlists

  music-client:
    image: tamland/airsonic-refix:latest
    container_name: music-clt
    restart: unless-stopped
    ports:
      - 5002:80

  feeds:
    container_name: feeds
    image: glanceapp/glance
    volumes: # Do not mount the entir app folder. It override the binary. 
      - ./apps/glance/config.yml:/app/glance.yml
      - ./apps/glance/assets:/app/assets
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 5003:8080
    restart: unless-stopped

  dev-tools:
    container_name: dev-tools
    image: 'corentinth/it-tools:latest'
    ports:
        - '5004:80'
    restart: unless-stopped
