version: "2.4"
services:

  filebrowser:
    container_name: filebrowser
    restart: unless-stopped
    volumes:
      - ./:/srv
      - ./.filebrowser/.data/:/data/
      - ./.filebrowser/config.json:/.filebrowser.json
    ports:
      - '4746:80'
    image: filebrowser/filebrowser

  music-server:
    image: sentriz/gonic:latest
    container_name: music-svr
    restart: unless-stopped
    ports:
      - 4747:80
    volumes:
      - ./music/.data:/data
      - ./music/:/music:ro
      - ./music/.playlists:/playlists

  music-client:
    image: tamland/airsonic-refix:latest
    container_name: music-clt
    restart: unless-stopped
    ports:
      - 4748:80

  # photo:
  #   image: photoprism/photoprism:latest
  #   container_name: photo
  #   restart: unless-stopped
  #   environment:
  #       - PHOTOPRISM_ADMIN_PASSWORD=tmp
  #   volumes:
  #       - ./photo/.data/:/photoprism/storage
  #       - ./photo/processed:/photoprism/originals
  #       - ./photo/import:/photoprism/import
  #   ports:
  #       - '4749:2342'

  it-tools:
    container_name: it-tools
    image: 'corentinth/it-tools:latest'
    ports:
        - '4750:80'
    restart: unless-stopped
